from dto.music import (
    MusicFileStats,
    Track,
    Artist,
    Album,
    NewAlbum,
    NewArtist,
    NewTrack,
    ArtistID,
    AlbumID,
    TrackID,
)
from dto.accounts import User, NewUser, UserID, NewRoleUser, UserUsername, LoginUserWithID

from typing import AsyncIterator, Protocol


class IMusicFileRepository(Protocol):
    async def save_track(
        self, track: Track, file_data: bytes, content_type: str
    ) -> None: ...

    async def save_image(
        self,
        image: Album | AlbumID | Artist | ArtistID,
        file_data: bytes,
        content_type: str,
    ) -> None: ...

    async def stream_track(
        self, track: Track, start: int, end: int
    ) -> AsyncIterator[bytes]: ...

    async def get_track_stats(self, track: Track) -> MusicFileStats: ...
    async def get_image(self, image: Album | AlbumID | Artist | ArtistID) -> bytes: ...
    async def delete_track(self, track: Track) -> None: ...
    async def delete_image(
        self, image: Album | AlbumID | Artist | ArtistID
    ) -> None: ...


class IArtistRepository(Protocol):
    async def create_artist(self, new_artist: NewArtist) -> Artist: ...
    async def get_artist_by_id(self, artist: ArtistID) -> Artist: ...
    async def get_artists(self, skip: int = 0, limit: int = 100) -> list[Artist]: ...
    async def update_artist(self, new_artist: Artist) -> Artist: ...
    async def delete_artist(self, artist: ArtistID) -> None: ...


class IAlbumRepository(Protocol):
    async def create_album(self, new_album: NewAlbum) -> Album: ...
    async def get_album_by_id(self, album: AlbumID) -> Album: ...
    async def get_albums_by_artist(
        self, artist: ArtistID, skip: int = 0, limit: int = 100
    ) -> list[Album]: ...
    async def get_albums(self, skip: int = 0, limit: int = 100) -> list[Album]: ...
    async def update_album(self, new_album: Album) -> Album: ...
    async def delete_album(self, album: AlbumID) -> None: ...


class ITrackRepository(Protocol):
    async def create_track(self, new_track: NewTrack) -> Track: ...
    async def get_track_by_id(self, track: TrackID) -> Track: ...
    async def get_tracks_by_artist(
        self, artist: ArtistID, skip: int = 0, limit: int = 100
    ) -> list[Track]: ...
    async def get_tracks_by_album(
        self, album: AlbumID, skip: int = 0, limit: int = 100
    ) -> list[Track]: ...
    async def get_tracks(self, skip: int = 0, limit: int = 100) -> list[Track]: ...
    async def update_track(self, new_track: Track) -> Track: ...
    async def delete_track(self, track: TrackID) -> None: ...


class IUserRepository(Protocol):
    async def create_user(self, new_user: NewRoleUser) -> User: ...
    async def get_user_by_id(self, user: UserID) -> User: ...
    async def get_user_by_username(self, user: UserUsername) -> LoginUserWithID: ...
    async def get_users(self, skip: int = 0, limit: int = 100) -> list[User]: ...
    async def update_user(self, new_user: User) -> User: ...
    async def delete_user(self, user: UserID) -> None: ...
