FROM python:3.12.1-slim-bullseye

COPY backend /app/backend
COPY .env /app/.env
WORKDIR /app

RUN pip install --no-cache-dir -r backend/requirements.txt

CMD ["python3", "-u", "backend/main.py"]