FROM python:3.12.1-slim-bullseye

COPY . /app
WORKDIR /app

COPY requirements.txt .
COPY .env .
RUN pip install --no-cache-dir -r requirements.txt

# CMD ["sh", "-c", "python migrations/apply.py && python -u main.py"]
CMD ["sh", "-c", "python migrations/apply.py && uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT}"]
# CMD ["sh", "-c", "set -a && . ./.env && set +a && python migrations/apply.py && uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT}"]