FROM bitnami/spark:latest


WORKDIR /app
COPY spark_etl/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
COPY spark_etl/ .
COPY .env .

ADD https://jdbc.postgresql.org/download/postgresql-42.6.0.jar /opt/spark/jars/

ENTRYPOINT ["/opt/spark/bin/spark-submit", "--master", "local[*]", "--packages", "org.mongodb.spark:mongo-spark-connector_2.12:10.1.1,org.postgresql:postgresql:42.6.0", "spark_etl/etl_job.py"]
