FROM bitnami/spark:latest

USER root

COPY spark_etl/ /app/spark_etl
WORKDIR /app

RUN pip install -r /app/requirements.txt

ADD https://jdbc.postgresql.org/download/postgresql-42.6.0.jar /opt/spark/jars/

ENTRYPOINT ["/opt/spark/bin/spark-submit", "--master", "local[*]", "--packages", "org.mongodb.spark:mongo-spark-connector_2.12:10.1.1,org.postgresql:postgresql:42.6.0", "spark_etl/etl_job.py"]
