apiVersion: apps/v1
kind: Deployment
metadata:
  name: slaymusic-backend
spec:
  replicas: $BACKEND_REPLICAS
  selector:
    matchLabels:
      app: slaymusic-backend
  template:
    metadata:
      labels:
        app: slaymusic-backend
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              check_service() {
                name="$1"
                host="$2"
                port="$3"
                echo -n "Waiting for $name..."
                until nc -z "$host" "$port" 2>/dev/null; do
                  sleep 0.25
                done
                echo " Done"
              }

              check_service "postgres-music-service" "postgres-music-service" "$MUSIC_PORT"
              check_service "mongodb-user-activity-service" "mongodb-user-activity-service" "$USER_ACTIVITY_PORT"
              check_service "minio-service" "minio-service" "$MINIO_PORT"
              check_service "redis-track-queue-service" "redis-track-queue-service" "$TRACK_QUEUE_PORT"

              echo "All dependencies are up!"
      containers:
        - name: slaymusic-backend
          image: slaymusic-backend-image
          command:
            [
              "sh",
              "-c",
              "uvicorn main:app --reload --host 0.0.0.0 --port ${BACKEND_PORT}",
            ]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: $BACKEND_PORT
          livenessProbe:
            httpGet:
              path: /misc/ping
              port: $BACKEND_PORT
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /misc/ping
              port: $BACKEND_PORT
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /misc/ping
              port: $BACKEND_PORT
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: slaymusic-backend-service
spec:
  selector:
    app: slaymusic-backend
  ports:
    - protocol: TCP
      port: $BACKEND_PORT
      targetPort: $BACKEND_PORT
  type: NodePort
