apiVersion: batch/v1
kind: Job
metadata:
  name: setup-job
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              check_service() {
                name="$1"
                host="$2"
                port="$3"
                echo -n "Waiting for $name..."
                until nc -z "$host" "$port" 2>/dev/null; do
                  sleep 0.25
                done
                echo " Done"
              }

              check_service "postgres-music-service" "postgres-music-service" "$MUSIC_PORT"
              check_service "minio-service" "minio-service" "$MINIO_PORT"
              check_service "redis-track-queue-service" "redis-track-queue-service" "$TRACK_QUEUE_PORT"

              echo "All dependencies are up!"
      containers:
        - name: setup-container
          image: slaymusic-setup-job-image
          command: ["sh", "-c"]
          args:
            - |
              alembic upgrade head && \
              python /app/setup/db_setup.py
          env:
            - name: PYTHONPATH
              value: "/app"
            - name: POSTGRES_USER
              value: $MUSIC_ROOT_USER
            - name: POSTGRES_PASSWORD
              value: $MUSIC_ROOT_PASSWORD
            - name: POSTGRES_DB
              value: $MUSIC_DB
      restartPolicy: OnFailure
  backoffLimit: 5
