name: Ruff Linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Ruff
      run: pip install ruff

    - name: Run Ruff on backend
      run: ruff check backend/

    - name: Run Ruff on tests
      run: ruff check tests/