name: Integrational Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2.14.0
      with:
        minikube version: 'v1.35.0'
        kubernetes version: 'v1.33.0'
        driver: docker

    - name: Install Tilt
      run: curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | sudo bash

    - name: Deploy with Tilt
      run: tilt ci --timeout 10m0s

    - name: Verify Backend Readiness
      run: |
        kubectl rollout status deployment/slaymusic-backend --timeout=3m
        kubectl port-forward deployment/slaymusic-backend 8000:8000 &
        sleep 3 
        curl -v http://localhost:8000/misc/ping
    
    - name: Install Python dependencies
      run: pip install -r tests/requirements.txt

    - name: Run Tests
      run: |
        pytest -v